# Generated by Django 6.0.5 on 2026-05-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Penerimaan'), ('AUTO', 'Pemakaian Otomatis')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='specification.material')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
