# Generated by Django 6.0.5 on 2026-05-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('roll_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='TyreSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tyre Specification',
                'verbose_name_plural': 'Tyre Specifications',
                'ordering': ['size', 'model'],
                'unique_together': {('size', 'model', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='specification.material')),
                ('tyre_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='specification.tyrespec')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'ordering': ['tyre_spec', 'material'],
                'unique_together': {('tyre_spec', 'material')},
            },
        ),
    ]
