# Generated by Django 6.0.5 on 2026-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='roll_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
