# Generated by Django 6.0.5 on 2026-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0003_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tyrespec',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
