# Generated by Django 6.0.5 on 2026-06-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
