# Generated by Django 6.0.5 on 2026-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_manager_to_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('purchasing', 'Admin Purchasing'), ('operator', 'Operator Gudang'), ('viewer', 'Manajemen')], default='viewer', max_length=20),
        ),
    ]
