# Generated by Django 6.0.5 on 2026-05-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=1)),
                ('pic', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Dikonfirmasi'), ('IN_PROGRESS', 'Sedang Berjalan'), ('DONE', 'Selesai')], default='DRAFT', max_length=20)),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=1)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_usages', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Daily Usage',
                'verbose_name_plural': 'Daily Usages',
                'ordering': ['-date', 'shift'],
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='DailyUsageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.dailyusage')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_usage_entries', to='specification.material')),
            ],
            options={
                'verbose_name': 'Daily Usage Entry',
                'verbose_name_plural': 'Daily Usage Entries',
                'ordering': ['daily_usage', 'material'],
                'unique_together': {('daily_usage', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_plan', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionorder')),
                ('tyre_spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='specification.tyrespec')),
            ],
            options={
                'verbose_name': 'Production Order Item',
                'verbose_name_plural': 'Production Order Items',
                'ordering': ['order', 'tyre_spec'],
                'unique_together': {('order', 'tyre_spec')},
            },
        ),
    ]
