# Generated by Django 6.0.5 on 2026-05-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('specification', '0002_roll_length_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyusage',
            options={'ordering': ['-date', 'shift']},
        ),
        migrations.AlterModelOptions(
            name='dailyusageentry',
            options={'ordering': ['daily_usage', 'material']},
        ),
        migrations.AlterModelOptions(
            name='productionorderitem',
            options={'ordering': ['order', 'tyre_spec']},
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Dikonfirmasi'), ('MAT_SENT', 'Material Dikirim'), ('IN_PROGRESS', 'Sedang Diproduksi'), ('RESULT_SENT', 'Hasil Dikirim'), ('DONE', 'Selesai')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_shipments', to='production.productionorder')),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='TyreDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_deliveries', to='production.productionorder')),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialShipmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specification.material')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.materialshipment')),
            ],
            options={
                'unique_together': {('shipment', 'material')},
            },
        ),
        migrations.CreateModel(
            name='TyreDeliveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_actual', models.PositiveIntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.tyredelivery')),
                ('tyre_spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specification.tyrespec')),
            ],
            options={
                'unique_together': {('delivery', 'tyre_spec')},
            },
        ),
    ]
