# Generated by Django 6.0.5 on 2026-06-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_materialshipment_confirmed'),
        ('specification', '0003_material_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_reserved', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='specification.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='production.productionorder')),
            ],
            options={
                'unique_together': {('order', 'material')},
            },
        ),
    ]
