# Generated by Django 6.0.5 on 2026-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_stock_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Dikonfirmasi'), ('MAT_SENT', 'Material Dikirim'), ('IN_PROGRESS', 'Sedang Diproduksi'), ('RESULT_SENT', 'Hasil Dikirim'), ('DONE', 'Selesai'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20),
        ),
    ]
